### PR TITLE
Add missing translations for discount trigger

### LINKED ISSUE #874: [Bug] Discount payment trigger don't show all options
The validity selector for the discounts is dependent on the translations present.
I have just realised this by testing the changes made by #854 PR.

image
vs
image

### PR DESCRIPTION
**Pull request by damsfx**
Fix #874

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Quick question: Do you actually speak all of these languages or how did you get these translations? :grin:

**Comment by damsfx** [comment]
Not all of them!
The Russian, Czech and Persian languages are totally unknown to me.
The translations I have provided are from online translators and would benefit from a little checking by someone who knows them.

For Italian, Portuguese and Spanish, even if I have some knowledge, I have asked people around me for help.

**Comment by damsfx** [comment]
On the other hand, even if the translations are not perfect, they at least have the advantage of showing all possible options for the trigger.  
Currently, this is not the case.

**Comment by tobias-kuendig** [comment]
Yes, absolutely. We need to refactor the getOptions method to not rely on the translations being available or not, this is the culprit of this problem.

**Comment by tobias-kuendig** [comment]
Thank you  for this PR! I have added a fix that does no longer rely on the translation strings in 6fbe455.

**Pull request closed without merging**
