### PR TITLE
WIP: Add property groups to products

### PR DESCRIPTION
**Pull request by mjauvin**

### CODE REVIEW

**Comment by mjauvin** [comment]
@tobias-kuendig did you get time to look into this PR to see if anything can be improved?

Thanks.

**Comment by tobias-kuendig** [comment]
Thank you for this PR @mjauvin 

I currently see two problems with this addition:

* It makes it more complicated to configure a product since a user now has two ways to add properties to a product
* The frontend is built around categories and this is how the product filters are generated. If I add a property X to a product, it won't be filterable in the frontend, only category filters are shown. Implementing this to work with Category and Product properties will not be easy.

I do wonder if this addition would be better suited as a plugin. We could add the required events to extend the functionality.

What do you think?

**Comment by mjauvin** [comment]
Yes, if I have all the hooks to do this, I have no problem to add the functionality as a plugin.

**Comment by mjauvin** [comment]
In fact, the only thing I can't extend dynamically is the SortableRelation trait on the product model.

**Pull request closed without merging**
