### PR TITLE
PostFinance PaymentProvider

### LINKED ISSUE #418: Postfinance payements
Please add if possible postfinance and datatrans for Switerzland.
Bests regards Alain Doudiet

### PR DESCRIPTION
**Pull request by tobias-kuendig**
I'm looking for testers here. Please report back any issues you find.

Don't forget to run `composer install` if you test this PR. 

fixes #418

### CODE REVIEW

**Comment by Zmove** [comment]
Tested : It works like a charm :)

Just saw a small error, you don't encrypt the right settings keys in encryptedSettings() method, and you don't use decrypt() to decrypt that encrypted settings.

**Comment by tobias-kuendig** [comment]
Thank you, good catch! I fixed this. You might have to clear the settings because it tries to decrypt your existing settings now, which will fail.

**Comment by tobias-kuendig** [comment]
Didn't get any more feedbac, so I guess this works okay. I'm going to release this later today.

**Comment by Zmove** [comment]
It's ok for me, tested and it works. The "complete()" method can be
improved with some payment status check, but it's already ok

Le jeu. 16 janv. 2020 à 07:29, Tobias Kündig <notifications@github.com> a
écrit :

**Comment by tobias-kuendig** [comment]
Do you have any docs on that check? Does Omnipay support it?

**Comment by Zmove** [comment]
[Here is the doc](https://e-payment-postfinance.ecom-psp.com/en/integration/all-sales-channels/integrate-with-e-commerce/guide).

Not sure if omnipay support, it, it seems it's role is to correctly redirect to the payment page by generating good $_POST variables + generate the correct SHASIGN value from that variables. But I'm not familiar with omnipay.

**Comment by tobias-kuendig** [comment]
Thanks, @Zmove. I added the complete purchase request here: 0f6738f

**Pull request merged**
