### PR TITLE
Update payment-providers.md

### PR DESCRIPTION
**Pull request by igor-tv**

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Thanks, but per October's docs custom classes belong into a `classes` folder, so the namespace should reflect that.

https://octobercms.com/docs/plugin/registration#directory-structure

**Comment by igor-tv** [comment]
Maybe I didn’t figure it out, but I thought that this piece is part of the Plugin.php code and you need to specify the plug-in namespace in it.

**Comment by igor-tv** [comment]
Thank you so much! 
I think it would be great if there was an example of how to connect one of the ready-made Omnipay Gateways from https://github.com/thephpleague/omnipay#payment-gateways

**Comment by igor-tv** [comment]
After installing your plugin, the directories mall/vendor/omnipay/paypal/src/RestGateway.php and others appear. I mean, there isn’t enough instructions on how to add similar Gateways for its payment providers to the user’s plugin.
pay

For example.
Install your payment provider Gateway:
`$ composer require league/omnipay: ^ 3 academe/omnipay-payone`

Without this, the user's payment method will not work, or am I wrong?

I installed the payment Gateway directly in the folder of my plugin and then included vendor/autoload.php in the boot method of the plugin.

By the way, how vendor / autoload.php is included in your plugin, I did not notice where this happens.

**Comment by tobias-kuendig** [comment]
You don't need to include the autoload.php manually. October/Laravel already handles all of this.

Simply create your own plugin, in the plugin folder, run `composer require omnipay/whatever` and create your Payment provider class.

Also, the vendor directory is shipped with plugins in October. Just ignore it. Add your dependencies to your plugin.

**Pull request closed without merging**
