### PR TITLE
Add secure downloads

### PR DESCRIPTION
**Pull request by PrestaSafe**
Add secure downloads for products in Mall. 
Capture d’écran 2019-09-09 à 09 20 23
User can download files in order details of front office: 
Capture d’écran 2019-09-09 à 09 21 28
The downloads are secured by custom route, it check if user is logged, if file depends of the good product and if the limite date in days is not passed. 

Design need to be adapted on front office. 
Thanks

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Thank you very much @PrestaSafe! This is a very great addition.

I will have a look at this PR in the comming days and will release an update if everything fits. :ok_hand:

**Comment by PrestaSafe** [comment]
You're welcome. 
I'll make the same for the variants products, i let you check this PR in a first time, if it's ok, i'll make the new one in a second time.

**Comment by tobias-kuendig** [comment]
Thank you very much for creating this PR @PrestaSafe.

Unfortunately, I cannot merge it into the main project since there are too many things that are missing (handling of shipping for virtual products, mail integration, dynamic generation of files for things like tickets, etc).

The plugin has reached an number of installations where we try to get every new feature "as right as possible" the first time. We also don't want to release incomplete solutions. This is why I won't include your work, but take it as inspiration for the feature to be written.

The virutal products feature is the next thing we will work on the upcomming days.

**Comment by tobias-kuendig** [comment]
You can track progress here:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/338

**Pull request closed without merging**
