### PR TITLE
Incremental pagination in ajax

### PR DESCRIPTION
**Pull request by inalto**
Hello,
I have added an incremental "load more" button to pull pages of products without reloading the full page.
A pratical mobile friendly navigation
Maybe you can find it useful feature to add

Here you can see it in action
https://www.quiyou.com/en/store/man?brand=emporio-armani&sort=bestseller
(Show more...) button

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Thank you for your contribution @inalto, but this PR contains too many changes. Please submit only the relevant change in a new PR.

**Comment by yellotra** [comment]
Hi Alan. I used your code, but I ran into one problem. If there are fewer products on the page than required for pagination or there are no products in the category at all, then the "show more" button is displayed (although it should not). If you click on it, it disappears.

**Comment by yellotra** [comment]
perhaps not the right decision - add {% if items.count >= 12 %}

12 - number items on page

<div class="mall-products" id="mall-products">
    {% partial __SELF__ ~ '::entries' %}
</div>

    <div class="mall-pagination mall-pagination--products">
        {% if paginate == '1' %}
        {{ items | raw }}
        {% endif %}
        {% if paginate == '2' %}
        <div id="mall-loadmore">
            {% partial __SELF__ ~ '::loadmore' %}
        </div>
        {% endif %}
    </div>

{% endif %}

{% partial __SELF__ ~ '::scripts' %}

**Comment by yellotra** [comment]
another dean, but a more serious bug. after a few clicks on the button, the number of products doubles, some of the products are duplicated from the previous click.

**Pull request closed without merging**
