### PR TITLE
Added CustomerPaymentMethods

### LINKED ISSUE #154: [Enhancement] Ability to send Customer Data when processing stripe payments
I'm not sure if you thought about it yet, but is there a way to send the customer data you collect with the stripe payment info? It would be lot easier to dispute charges (if any) when you have the data in their system.

### PR DESCRIPTION
**Pull request by tobias-kuendig**
Corresponding theme changes:

https://github.com/OFFLINE-GmbH/oc-mall-theme/commit/509d2b2899073fc03dc91923d2c8ad011e9adf27

Fixed #154

### CODE REVIEW

**Comment by artistro08** [comment]
I wasn't able to test this. Couldn't get it to work in my environment. Is it ready to be merged?

**Comment by tobias-kuendig** [comment]
I'm releasing this as an edge update. It would be great to have someone test the new feature using October's edge update channel.

**Comment by artistro08** [comment]
awesome. Will be testing this later tonight!


On 3/25/2019 6:57:55 AM, Tobias Kündig <notifications@github.com> wrote:
I'm releasing this as an edge update. It would be great to have someone test the new feature using October's edge update channel.

**Comment by artistro08** [comment]
So it worked! It did create a customer in the stripe dashboard. Now, the only thing that I think is missing is sending the billing address with the email and we should be set! I tested this on my local workstation with the Mall Theme. Worked really well. 

I also tested this with my own theme. It saves the card information as expected if they are logged in

**Comment by tobias-kuendig** [comment]
Thank you very much for testing. I'll try to add the addresses as well. The omnipay docs are a bit sparse on that.

**Comment by artistro08** [comment]
No worries.

**Comment by tobias-kuendig** [comment]
Omnipay currently does not support the `shipping` data to be sent to Stripe.

I've created [a PR that adds this feature](https://github.com/thephpleague/omnipay-stripe/pull/120). If it gets merged we will have support for it as soon as a new Omnipay version is released. The current version of the mall plugin is already providing all needed information.

**Pull request merged**
