### PR TITLE
fixes for translate plugin v2.0

### PR DESCRIPTION
**Pull request by c2webstudio**
This fix has **breaking changes** when used with translate plugin prior to v2.0.

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Thank you very much @c2webstudio! I'll review these changes and publish a new major version of the plugin.

**Comment by tobias-kuendig** [comment]
Thank you @c2webstudio!

**Comment by damsfx** [comment]
@mjauvin This PR will introduce a breaking change with WinterCMS, no?

**Comment by mjauvin** [comment]
Indeed, unless RainLab.Translate plugin is used.

Also, Winter.Translate replaces RainLab.Translate <= 1.9.0

**Pull request merged**
